name: "Pre-Release Workflow"

on:
  workflow_dispatch:
    inputs:
      release_version:
        type: string
        description: pre-release version when building docker containers (example; 2.0.0-beta.1)

run-name: >-
  ${{ format('Pre-Release {0}', github.event.inputs.release_version) }}
        
jobs:
  pre-release:
    name: Pre-Release Docker Image Build
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout code
      uses: actions/checkout@v4
          
    - name: Create tag
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/${{ github.event.inputs.release_version }}',
            sha: context.sha
          })
    - name: Update local repo after tag creation
      run: |
        git fetch --all --tags
        git pull

    - name: Generate Release Changelog
      id: changelog
      uses: mikepenz/release-changelog-builder-action@v4
      with:
        configuration: '.github/changelog-configuration.json'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build project
      run: npm ci && npm run build

    - name: Zip out folder
      run: |
        if [ -d "out" ]; then
          zip -r release.zip out
        else
          echo "No out folder found to zip."
        fi

    - name: Create Pre-Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.release_version }}
        name: Pre-Release v${{ github.event.inputs.release_version }}
        body: ${{ steps.changelog.outputs.changelog }}
        draft: false
        prerelease: true
        files: release.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
